project:
  type: website
  output-dir: "docs"

website:
  title: "World Economic History Congress 2025"
  favicon: assets/favicon.ico
  navbar:
    # background: "#a1c993"
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: "Calls"
        menu:
          - news/call-for-posters.qmd
          - news/call-for-dissertations.qmd
          - news/call-for-sessions.qmd
          - news/call-for-sessions-member-associations.qmd
      - href: "#"
        text: "Test Button"  # The test button

    right:
      - href: content/contact.qmd
      - href: "https://visitlund.se/en"
        text: "Visit Lund"
