project:
  type: website
  output-dir: "docs"

website:
  title: "World Economic History Congress 2025"
  favicon: assets/favicon.ico
  navbar:
    # background: "#a1c993"
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: "Calls"
        menu:
          - news/call-for-sessions.qmd
          - news/call-for-sessions-member-associations.qmd

    right:
      # - href: content/look-and-feel.qmd
      - href: content/contact.qmd
      # - href: content/practical-information.qmd
      - href: "https://visitlund.se/en"
        text: "Visit Lund"

format:
  html:
    theme:
    - flatly
    - assets/custom.scss
    css: styles.css
    toc: true

editor: source

execute:
  freeze: true
  echo: false

