---
title: "{{< fa solid house >}} Information on accommodations"
format: html
description: "Learn the latest details on accommodations for the conference."
date: 2024-09-29
---

The standard of accommodation in the Lund region is broad, ranging from hostels to first-class hotel accommodations. The hotel capacity in Lund is 1,600 rooms, and accommodation will be booked well in advance for the WEHC. In nearby Malmö (10 minutes by train), the hotel capacity is 5,000 rooms, which may also be used for the WEHC.

For budget travelers, there are several hostels and Airbnb options in Lund, as well as student rooms with a good standard that will be available during the conference. 

Specific conference rates for WEHC 2025 are displayed below:

## Hotel Offers WEHC 28/7—1/8 2025

| Hotel                | # of rooms | Price/Single room (SEK) | Price/Double room (SEK)               | How to book?                                                                                                                                       |
|----------------------|-----------|----------------|------------------------------------- |-----------------------------------------------------------------------------------------------------------------------------------------------|
| Hotel Concordia       | 48        | 1595           | 1845                                | Email info@concordia.se. Use the code: "World Economic History Congress"                                                                |
| Hotel Lundia          | 60        | 1195           | 1395                                | [Click here](https://reservations.travelclick.com/86335?groupID=4381903)                                                                        |
| Hotel Nordic          | 30        | 1395           | 1595                                | Email info@nordiclund.se. Use the code: 066245                                                                                 |
| Motell L              | 80        | 995            |                                     | [Click here](https://redirects.ligula.se/WorldEconomicHistoryCongress2025)                                                                      |
| Elite Hotel Ideon*    | 60        |                | 1057/1270/1312                      | [Click here](https://visitlund.se)                                                                                                |
| **Total**             | **278**   |                |                                     |                                                                                                                                               |

**Prices include fees and breakfast.**
**Unbooked rooms will be available at these prices until 30/06.**
