---
title: "{{< fa dove >}} Just a kind reminder..."
format: html
description: ...to be an early bird!
date: 2025-01-29

---

Dear colleagues,

I hope this message finds you well. As part of the organizing committee for the World Economic History Congress 2025, I would like to remind you of a few important steps to ensure the smooth organization of the sessions.

A preliminary schedule is now available on the conference website, and we kindly ask you to review it. For the time being, only the names of the organizers and participants are available. Please confirm the names of all participants in the session you are organizing, and ensure that their presentation or paper titles, as well as their affiliations, are added to the session information. Editing the session details can be done directly through the submission portal. We encourage you to do this as soon as possible, but not later than March 15th. Timely updates not only assist us in allocating rooms appropriately but also enable us to publish the final schedule earlier, which will help participants plan their travel arrangements more effectively.

Additionally, we would like to remind you that February 15th is the deadline for early bird registration. If you or your participants wish to take advantage of this option, please ensure that registration is completed before this date. If you cannot pay by card or need your employer/funder to pay on your behalf, we can issue invoices. If this is the case, please, message the organizing committee directly so we can assist you.

If you have any additional questions or need further assistance, please feel free to contact us at [wehc2025@ekh.lu.se](mailto:wehc2025@ekh.lu.se). We look forward to welcoming you to Lund in 2025!

<div style="line-height:1.2;">
On behalf of the WEHC 2025 Organizing Committee<br>
Igor Martins<br>
Senior Lecturer<br>
Department of Economic History, Lund University
</div>
