---
title: "{{< fa solid clipboard >}} Call for posters"
format: html
description: "Invitation to submit posters for the WEHC 2025."
date: 2024-09-18
---

The Poster Exhibition enables scholars in Economic history to present their latest research projects. We kindly invite you to exhibit your ongoing work through the submission of a Poster. The Poster Exhibition will be active Monday – Wednesday (28–30 July) from 13.00–14:00 in connection with the lunches, right in the heart of the congress mingle.

You are invited to submit a short abstract, which will be proofed and selected by a Poster Selection Committee. Priority will be given to young scholars, but seniors are also invited. The committee will also select a winner for Best WEHC Poster 2025, to be announced at the congress festivities on 30 July.

**The deadline for proposals is 10 December 2024**. Please email your abstract to [wehc2025@ekh.lu.se](mailto:wehc2025@ekh.lu.se). Enter "Poster proposal" in the subject field. The mail must state your name, affiliation, title of the Poster, and an abstract no longer than 400 words. Accepted Posters will be announced before 10 January 2025, together with details on the physical format of the exhibits.
