---
title: "{{< fa people-group >}} Call for sessions"
format: html
description: We have a particularly strong desire to attract sessions related to the theme `Equality and Sustainability Challenges`. However, submissions are welcome on the economic and social histories of all places and periods, and on the exploration of varied sources and methods, and on the theory and uses of economic history itself.
date: 2023-09-13

---

The 20th World Economic History Congress will convene from 28 July–1 August 2025 in Lund, Sweden. The theme for the Congress is `Equality and Sustainability Challenges`, which highlights some of the central issues facing humanity today and also connects to a broad and diverse range of historical problems. To address both the challenges and to find insights from the historical record for that endeavour, a range of perspectives will be necessary.

The IEHA has a particularly strong desire to attract sessions related to this theme. However, submissions are welcome on the economic and social histories of all places and periods, and on the exploration of varied sources and methods, and on the theory and uses of economic history itself. We also invite members to employ and analyse diverse strategies for representing the past.

Sessions may be proposed by any member of the international economic history community, whatever their institutional affiliation or status, as well as by scholars in related disciplines. Given the diversity of our membership, we will consider any submission that advances the study, teaching and public presentation of economic history. We welcome panel proposals that highlight scholarship emerging from economic history, business history, financial history, demographic history, environmental history, global and world history, social history, urban and agrarian history, gender studies, material culture, methodological approaches to historical research, history of economics and economic thought, science and technology studies, and other related fields.  

The programme of the Lund Congress will be organised on the same principles as previous Congresses. The 5-day Congress will have approximately 180 sessions, with each day divided into time blocks of 90 minutes each (two before lunch and two after lunch). As in the past, it will be possible to combine two sessions into larger coherent units. 

The session proposals should contain:


- Name, title, affiliation, and contact information of the session organiser
- Possible co-organisers (optional)
- Title of the session
- Description of the session’s aim, contribution, and relevance (max 5,000 characters with blanks)
- Researchers invited to participate in the session, or those already confirmed, and their affiliations


The deadline for submissions is now closed. If you want to edit your submission, please, visit [this link](https://www.appinconf.com/kas/Abstract?projectName=wehc2025). If you have any further questions, message the organizing committee at wehc2025@ekh.lu.se.
