---
title: "{{< fa people >}} Keynote speakers"
format: html
description: Keynote speakers revealed!
date: 2024-11-04
---

Elise van Nederveen Meerkerk is a professor of economic and social history and chair of the Economic and Social History group at Utrecht University, The Netherlands. She specializes in Global Labour History, with a focus on gendered and colonial labour relations. Apart from journal articles in Feminist Economics, Economic History Review, and the European Review of Economic History, Elise published a monograph entitled Women, Work and Colonialism in the Netherlands and Java. Comparisons, Contrasts, Connections, 1830-1940 (Palgrave Macmillan, 2019). She was PI of the EU-funded ERC Consolidator research project “Race to the Bottom? Family Labour, Household Livelihood and Consumption in the Relocation of Global Cotton Manufacturing, ca. 1750-1990”. Currently, Elise is developing a new research project on coerced labour in the Dutch Empire. At WEHC 2025, Professor van Nederveen Meerkerk will give a keynote with the title Work, Gender, Race and Class: Towards Intersectional Political Economics?

Mar Rubio-Varas is a Professor of History and Economic Institutions at Universidad Publica de Navarra (UPNA, Spain), She specializes in the long-term relationships between energy consumption and the economy, focusing on energy dependency and transitions to low-carbon economies. She holds a PhD and Master’s from the London School of Economics and a degree in Economics from Carlos III University. Rubio-Varas leads a team researching the take-off of renewable industry in Navarra and other European regions and her research includes directing multiple EU-funded projects. Her recent publications include articles in, Ecological Economics, the Journal of Contemporary History, Energy Journal, Energy Policy, Economic History Review and European Review of Economic History. Among her publications is a book on the Spanish nuclear sector (Palgrave MacMillan, 2017). At WEHC 2025, Professor Rubio-Varas will give a keynote with the title Greening the Past, Informing the Future: Economic History's Dual Role in Sustainability Challenges.

César A. Hidalgo is known for his contributions to economic complexity and for his applied work on data visualization and artificial intelligence. Hidalgo is a tenured professor at the Toulouse School of Economics’ Department of Social and Behavioral Sciences and the head of the Center for Collective Learning a multidisciplinary research laboratory. He is also an Honorary Professor at the Alliance Manchester Business School of the University of Manchester. Hidalgo’s contributions have been recognized with numerous awards, including the 2018 Lagrange Prize and three Webby Awards. Hidalgo's has authored dozens of peer-reviewed papers and of three books: Why Information Grows (Basic Books, 2015), The Atlas of Economic Complexity (MIT Press, 2014), and How Humans Judge Machines (MIT Press, 2021). His next book, The Infinite Alphabet (Penguin-Random House, 2025) is scheduled for the summer of 2025. At WEHC 2025, Professor Hidalgo will give a keynote with the title Big Data and Machine Learning Explorations of Economic History and Collective Memory.

