---
title: "Call for sessions: member associations"
---

The 20th World Economic History Congress will convene from 28 July– August 2025 in Lund, Sweden. As a new initiative, the IEHA invites session proposals from member associations. Sessions can be on any area of economic and social history, but should aim to highlight work by scholars affiliated to member associations – whether those are defined thematically or geographically. 

Association sessions allow our member organizations to showcase the work of their scholars in front of a global audience, engaging with new potential members. It also enables member organizations to host meetings without incurring the overhead costs of renting space or 
basis. 

Other opportunities for member associations to publicise their activities at the meeting will include a dedicated table in the publishers’ area where associations can display literature or copies of their journals. There will also be meeting space available during the breaks for member associations to hold their own organizational meetings. 

The member society session proposals should contain:


- Name of the member society proposing the session
- Contact information
- Title of the session
- Description of the session’s aim, contribution, and relevance (max 5,000 characters with blanks)
- Researchers invited to participate in the session, or those already confirmed, and their affiliations
- Preferred date and time of the session
 
Member associations should submit their sessions by January 31, 2024 via the portal at [this link](https://www.appinconf.com/kas/Abstract?projectName=wehc2025members). Decisions will be finalised in June 2024. Please note that only Associations which are up-to-date with their membership fees will be eligible to submit a proposal for a member association. Decisions will be finalised in June 2024. 
