---
title: "Participation grants"
---

To promote participation from regions normally less represented at international scientific conferences, the WEHC 2025 has set up a significant support scheme for scholars who have less access to funding than those from OECD countries. Grant holders may present a paper, organize or chair a session, present a Poster, or simply attend the Congress, but priority will be given to those who will play an active part.

The organizing committee will offer up to 80 grants to fully cover the Congress registration fee and five nights’ accommodation in Lund. Eligible are junior and senior scholars who have difficulties getting support from their university or research unity. The WEHC 2025 Organising Committee will evaluate the cost differential between the candidate’s country of origin or professional practice and Sweden. The grant will not involve any cash flow to the recipient, who will be given a special code for the Congress registration fee (not for the meals) and prepaid accommodation at Lund University Guest House, Sparta, a 15-minute walk from the Congress venues.

Apply by sending an email with a short CV (max. 3,000 signs) to [wehc2025@ekh.lu.se](mailto:wehc2025@ekh.lu.se). State your planned activity during the Congress or if you simply will attend. Enter “Participation grant” in the subject field. The latest day for application is 1 January 2025. If you are applying for this grant, wait with your WEHC registration until we get back to you with a decision and further instructions. Already paid registration fees will not be reimbursed.
