---
title: "Travel information"
---

There are many ways through which you can reach the conference in Lund.

## Airline access
The closest international airport to Lund is Copenhagen Airport (CPH), in Denmark. It’s the most accessible airport in Scandinavia and most international airlines operate into it. The airport is only a 40-minute train ride from Lund and takes you over the Oresund Bridge connecting Denmark to Sweden.

## Train access
International train connections are available mainly to Copenhagen Central Station, from where regional trains depart for Lund, passing by the airport on the way. Lund is also a major stop on the national Swedish railway system, e.g., a four-hour ride from Stockholm.

## Public Transport
Public transport in Sweden in general, and in the Malmö/Lund/Copenhagen region in particular, is modern, very accessible, and convenient. Local trains run frequently (every 5–10 min) between Lund-Malmö and every 20 min between Lund and Copenhagen. The WEHC area is less than a 10-minute walk from Lund railway station. Within the town of Lund, the city buses and trams are easily accessible and offer convenient transportation with good pricing, reaching all parts of Lund.

In the town center of Lund, the most convenient way of transportation is walking or bicycling.
