on: 
  push:
    branches:
      - main

name: Render and Publish

permissions: 
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Cache R packages (Updated to v4)
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/R
          key: ${{ runner.os }}-R-${{ hashFiles('**/*.R*', '**/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-R-

      # Install R packages (only installs packages if not cached)
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown"), repos="https://cran.rstudio.com")'

      # Render the Quarto project
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      # Commit and push changes back to the repository
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "rerender site"

      # Fix: Use a maintained GitHub Action for pushing changes
      - name: Push changes
        uses: actions-x/commit@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      # Optional publishing step (uncomment for GitHub Pages or Netlify)
      # - name: Publish to GitHub Pages
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
