on:
    push:
      branches:
        - main
  
name: Render and Publish
  
  # you need these permissions to publish to GitHub pages
  # permissions: 
  #     contents: write
  #     pages: write
  
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
          
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            # To install LaTeX to build PDF book 
            tinytex: true 
            # uncomment below and fill to pin a version
            # version: SPECIFIC-QUARTO-VERSION-HERE
        
        # Set up R
        - name: Setup R
          uses: r-lib/actions/setup-r@v2

        - name: Install R packages
          run: |
            Rscript -e 'install.packages(c("knitr", "rmarkdown"), repos="https://cran.rstudio.com")'

        # Render the Quarto project
        - name: Render Quarto Project
          uses: quarto-dev/quarto-actions/render@v2
          
        # Commit and push changes back to the repository
        - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "rerender site" --allow-empty)

        - name: Push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main

        # Optional publishing step (for Netlify or GitHub Pages)
        # Uncomment if you want to publish to GitHub Pages or Netlify

        # - name: Publish to GitHub Pages (and render)
        #   uses: quarto-dev/quarto-actions/publish@v2
        #   with:
        #     target: gh-pages
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # - name: Publish to Netlify (and render)
        #   uses: quarto-dev/quarto-actions/publish@v2
        #   with:
        #     target: netlify
        #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
